version: "3.7"

services:
  mysql:
    container_name: ${CONTAINER_NAME}_mysql
    image: mysql:5.7
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      MYSQL_DATABASE: '${MYSQL_DBNAME}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    volumes:
      - 'mysql:/var/lib/mysql'
    restart: always

  adminer:
    container_name: ${CONTAINER_NAME}_adminer
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - '${ADMINER_PORT}:8080'

volumes:
  mysql:
