version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4-apache-node-browsers

    steps:
      - checkout

      - run: sudo apt update && sudo apt install -y libsqlite3-dev zlib1g-dev openssl
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update

      - restore_cache: # special step to restore the dependency cache if `composer.lock` does not change
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found (See https://circleci.com/docs/2.0/caching/)
            - composer-v1-
      - run: composer install -n --optimize-autoloader --classmap-authoritative
      - run: composer dump-autoload --optimize --classmap-authoritative
      - save_cache: # special step to save the dependency cache with the `composer.lock` cache key template
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      - run: vendor/bin/phpcs
      - run: vendor/bin/phpcbf
      - run: vendor/bin/phpstan analyse src
      - run: vendor/bin/phpmd src xml phpmd.xml

      - run: mkdir -p config/jwt
      - run: openssl genpkey -out config/jwt/private-test.pem -aes256 -algorithm rsa -pkeyopt rsa_keygen_bits:4096 -pass pass:$JWT_PASSPHRASE
      - run: openssl pkey -in config/jwt/private-test.pem -out config/jwt/public-test.pem -pubout -passin pass:$JWT_PASSPHRASE

      - run: php bin/phpunit
      - run: vendor/bin/behat
